/*
 * Copyright (c) 2011 Stephen A. Pratt
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
using System;
using org.critterai.geom;

namespace org.critterai.nmgen
{
    /// <summary>
    /// Provides a way of building <see cref="PolyMesh"/>
    /// and <see cref="PolyMeshDetail"/> data from source geometry in 
    /// an incremental manner.
    /// </summary>
    /// <remarks>
    /// <para>This class is useful for instances where not all the build steps
    /// should occur in a single step.  (Such as when a GUI needs to
    /// provid feedback.)  The time to perform each increment will not be
    /// equal.  Rather the increments are broken down by steps in the build
    /// process.  E.g. Voxelize geometry, build regions, etc.</para>
    /// <para>Each instance can be used to perform only a single build.</para>
    /// </remarks>
    public sealed class IncrementalBuilder
    {
        private const string pre = "PolyMesh Build: ";
        private const string pret = pre + "Trace: ";

        private NMGenParams mConfig;
        private BuildFlags mFlags;
        private BuildState mState;
        private BuildContext mContext;
        private bool mTrace;

        private Object mPrimary;
        private Object mSecondary;

        /// <summary>
        /// The current state of the builder.
        /// </summary>
        /// <remarks>
        /// If the value is an unfinished state, then it represents the 
        /// build step that will occur the next time the <see cref="Build"/> 
        /// method called.
        /// </remarks>
        public BuildState State { get { return mState; } }

        /// <summary>
        /// TRUE if the the build has finished.  (Successfully or not.)
        /// </summary>
        public bool IsFinished
        {
            get
            {
                return (mState == BuildState.Aborted
                    || mState == BuildState.Complete);
            }
        }

        /// <summary>
        /// The <see cref="PolyMesh"/> created by the build, or NULL if no
        /// mesh is available.
        /// </summary>
        public PolyMesh PolyMesh
        {
            get
            {
                if (mState == BuildState.Complete)
                    return (PolyMesh)mPrimary;
                return null;
            }
        }

        /// <summary>
        /// The <see cref="PolyMeshDetail"/> created by the build, or NULL
        /// if no mesh is available.
        /// </summary>
        public PolyMeshDetail DetailMesh
        {
            get
            {
                if (mState == BuildState.Complete)
                    return (PolyMeshDetail)mSecondary;
                return null;
            }
        }

        /// <summary>
        /// The number of messages generated by the build.
        /// </summary>
        public int MessageCount { get { return mContext.MessageCount; } }

        /// <summary>
        /// Constructor
        /// </summary>
        /// <remarks>
        /// <para>WARNING: Don't forget to set the easily overlooked tile size
        /// and bounds properties in the <paramref name="config"/>
        /// object!  These properties don't have any valid default values 
        /// and using the configuration without setting them will result in 
        /// empty meshes.
        /// </para>
        /// </remarks>
        /// <param name="trace">TRUE if detailed trace messages should be
        /// recored during the build process.</param>
        /// <param name="config">The build configuration.</param>
        /// <param name="buildFlags">Flags indicating which optional build
        /// steps to include.</param>
        /// <param name="source">The source geometry.</param>
        public IncrementalBuilder(bool trace
            , NMGenParams config
            , BuildFlags buildFlags
            , TriangleMesh source)
        {
            mContext = new BuildContext(true);

            if (config == null
                || source == null
                || source.triCount < 1)
            {
                mState = BuildState.Aborted;
                mContext.Log(pre + 
                    "Aborted at construction. Null parameters or no geometry.");
                return;
            }

            mTrace = trace;
            mConfig = config.Clone();
            mConfig.DeriveSizeOfGrid();

            mFlags = buildFlags;
            mPrimary = source;

            mState = BuildState.MarkWalkableTris;
        }

        /// <summary>
        /// Gets available build messages, or a zero length array if no messages
        /// are available.
        /// </summary>
        /// <returns>Available build messages.</returns>
        public string[] GetMessages() { return mContext.GetMessages(); }

        /// <summary>
        /// Performs a single build step.
        /// </summary>
        /// <remarks><para>The result state will represent either a finished state
        /// or the build step that will be performed during the next call to
        /// the method.</para></remarks>
        /// <returns>The state at the end of the build step.</returns>
        public BuildState Build()
        {
            switch (mState)
            {
                case BuildState.MarkWalkableTris:
                    MarkWalkableTris();
                    break;
                case BuildState.HeightfieldBuild:
                    BuildHeightfield();
                    break;
                case BuildState.CompactFieldBuild:
                    BuildCompactField();
                    break;
                case BuildState.MarkSpans:
                    MarkSpans();
                    break;
                case BuildState.ErodeWalkableArea:
                    ErodeWalkableArea();
                    break;
                case BuildState.DistanceFieldBuild:
                    BuildDistanceField();
                    break;
                case BuildState.RegionBuild:
                    BuildRegions();
                    break;
                case BuildState.ContourBuild:
                    BuildContours();
                    break;
                case BuildState.PolyMeshBuild:
                    BuildPolyMesh();
                    break;
                case BuildState.DetailMeshBuild:
                    BuildDetailMesh();
                    break;

            }
            return mState;
        }

        private void MarkWalkableTris()
        {
            TriangleMesh source = (TriangleMesh)mPrimary;

            byte[] areas = new byte[source.triCount];

            NMGen.MarkWalkableTriangles(mContext
                , source
                , mConfig.walkableSlope
                , areas);

            if (mTrace)
                mContext.Log(pret + "Marked walkable triangles");

            mSecondary = areas;
            mState = BuildState.HeightfieldBuild;
        }

        private void BuildHeightfield()
        {
            Heightfield hf = new Heightfield(mConfig.width
                , mConfig.depth
                , mConfig.boundsMin
                , mConfig.boundsMax
                , mConfig.xzCellSize
                , mConfig.yCellSize);

            hf.AddTriangles(mContext
                , (TriangleMesh)mPrimary
                , (byte[])mSecondary
                , mConfig.walkableStep);  // Merge for any spans less than step.

            if (mTrace)
                mContext.Log(pret + "Voxelized triangles. Span count: " 
                    + hf.GetSpanCount());

            if (hf.GetSpanCount() < 1)
            {
                mContext.Log("Aborted after heightfield build."
                    + " Heightfield does not have any spans.");
                mState = BuildState.Aborted;
                return;
            }

            mPrimary = hf;
            mSecondary = null;

            if ((mFlags
                & (BuildFlags.LowObstaclesWalkable
                    | BuildFlags.LedgeSpansNotWalkable
                    | BuildFlags.LowHeightSpansNotWalkable)) != 0)
            {
                mState = BuildState.MarkSpans;
            }
            else
                mState = BuildState.CompactFieldBuild;
        }

        private void MarkSpans()
        {
            Heightfield hf = (Heightfield)mPrimary;

            if ((mFlags & BuildFlags.LowObstaclesWalkable) != 0
                && mConfig.walkableStep > 0)
            {
                hf.MarkLowObstaclesWalkable(mContext, mConfig.walkableStep);
                if (mTrace)
                    mContext.Log(pret + "Flagged low obstacles as walkable.");

            }

            if ((mFlags & BuildFlags.LedgeSpansNotWalkable) != 0)
            {
                hf.MarkLedgeSpansNotWalkable(mContext
                    , mConfig.walkableHeight
                    , mConfig.walkableStep);
                if (mTrace)
                    mContext.Log(pret + "Flagged ledge spans as not walklable");
            }

            if ((mFlags & BuildFlags.LowHeightSpansNotWalkable) != 0)
            {
                hf.MarkLowHeightSpansNotWalkable(mContext
                    , mConfig.walkableHeight);
                if (mTrace)
                    mContext.Log(pret
                        + "Flagged low height spans as not walkable.");
            }

            mState = BuildState.CompactFieldBuild;

        }

        private void BuildCompactField()
        {
            Heightfield hf = (Heightfield)mPrimary;

            CompactHeightfield chf = CompactHeightfield.Build(mContext
                , hf
                , mConfig.walkableHeight
                , mConfig.walkableStep);

            hf.RequestDisposal();
            mPrimary = null;

            if (chf == null)
            {
                mContext.Log(pre + "Aborted at compact heightfield build.");
                mState = BuildState.Aborted;
                return;
            }

            if (mTrace)
                mContext.Log(pret + "Built compact heightfield. Spans: " 
                    + chf.SpanCount);

            if (chf.SpanCount < 1)
            {
                mContext.Log("Aborted after compact heightfield build."
                    + " Heightfield does not have any spans.");
                mState = BuildState.Aborted;
                return;
            }

            mSecondary = chf;

            if (mConfig.walkableRadius > 0)
                mState = BuildState.ErodeWalkableArea;
            else
                mState = BuildState.DistanceFieldBuild;
        }

        private void ErodeWalkableArea()
        {
            CompactHeightfield chf = (CompactHeightfield)mSecondary;

            chf.ErodeWalkableArea(mContext, mConfig.walkableRadius);

            if (mTrace)
                mContext.Log(pret + "Eroded walkable area by radius.");

           mState = BuildState.DistanceFieldBuild;
        }

        private void BuildDistanceField()
        {
            CompactHeightfield chf = (CompactHeightfield)mSecondary;

            chf.BuildDistanceField(mContext);
            if (mTrace)
                mContext.Log(pret + "Built distance field. Max Distance: "
                    + chf.MaxDistance);

            mState = BuildState.RegionBuild;
        }

        private void BuildRegions()
        {
            CompactHeightfield chf = (CompactHeightfield)mSecondary;

            if ((mFlags & BuildFlags.UseMonotonePartitioning) != 0)
            {
                chf.BuildRegionsMonotone(mContext
                    , mConfig.borderSize
                    , mConfig.minRegionArea
                    , mConfig.mergeRegionArea);
                if (mTrace)
                    mContext.Log(pret + "Built monotone regions.");
            }
            else
            {
                chf.BuildRegions(mContext
                    , mConfig.borderSize
                    , mConfig.minRegionArea
                    , mConfig.mergeRegionArea);
                if (mTrace)
                    mContext.Log(pret + "Built regions. Region Count: "
                        + chf.MaxRegion);
            }

            if (chf.MaxRegion < 2)
            {
                // Null region counts as a region.  So expect
                // at least 2.
                mContext.Log("Aborted after region build."
                    + " No useable regions formed.");
                mState = BuildState.Aborted;
                return;
            }

            mState = BuildState.ContourBuild;
        }

        private void BuildContours()
        {
            ContourBuildFlags cflags =
                (ContourBuildFlags)((int)mFlags & 0x03);

            ContourSet cset = ContourSet.Build(mContext
                , (CompactHeightfield)mSecondary
                , mConfig.edgeMaxDeviation
                , mConfig.maxEdgeLength
                , cflags);

            if (cset == null)
            {
                mContext.Log(pre + "Aborted at contour set build.");
                mState = BuildState.Aborted;
                return;
            }

            if (mTrace)
                mContext.Log(pret + "Build contour set. Contour count: "
                    + cset.Count);

            if (cset.Count < 1)
            {
                mContext.Log("Aborted after contour build."
                    + " No contours were generated.");
                mState = BuildState.Aborted;
                return;
            }

            mPrimary = cset;

            mState = BuildState.PolyMeshBuild;
        }

        private void BuildPolyMesh()
        {
            ContourSet cset = (ContourSet)mPrimary;

            PolyMesh polyMesh = PolyMesh.Build(mContext
                , cset
                , mConfig.maxVertsPerPoly
                , mConfig.walkableHeight
                , mConfig.walkableRadius
                , mConfig.walkableStep);

            cset.RequestDisposal();

            if (polyMesh == null)
            {
                mContext.Log(pre + "Aborted at poly mesh build.");
                mState = BuildState.Aborted;
                return;
            }

            if (mTrace)
                mContext.Log(pret + "Built poly mesh. PolyCount: "
                    + polyMesh.PolyCount);

            if (polyMesh.PolyCount < 1)
            {
                mContext.Log(pre + "Aborted after poly mesh build."
                    + "No polygons were generated.");
                mState = BuildState.Aborted;
                return;
            }

            if ((mFlags & BuildFlags.ApplyPolyFlags) != 0)
            {
                PolyMeshData data = polyMesh.GetData(false);
                for (int i = 0; i < data.flags.Length; i++)
                {
                    data.flags[i] = NMGen.DefaultFlag;
                }

                polyMesh.Load(data);
                if (mTrace)
                    mContext.Log(pret 
                        + "Applied polymesh flag to all polys: 0x01");
            }
            mPrimary = polyMesh;

            mState = BuildState.DetailMeshBuild;
        }

        private void BuildDetailMesh()
        {
            PolyMesh polyMesh = (PolyMesh)mPrimary;
            CompactHeightfield chf = (CompactHeightfield)mSecondary;

            PolyMeshDetail detailMesh = PolyMeshDetail.Build(mContext
                , polyMesh
                , chf
                , mConfig.detailSampleDistance
                , mConfig.detailMaxDeviation);

            chf.RequestDisposal();

            if (detailMesh == null)
            {
                mContext.Log(pre + "Aborted at detail mesh build.");
                polyMesh.RequestDisposal();
                mPrimary = null;
                mSecondary = null;
                mState = BuildState.Aborted;
                return;
            }

            mSecondary = detailMesh;

            if (mTrace)
                mContext.Log(pret + "Built detail mesh. TriangleCount: "
                    + detailMesh.TriCount);

            if (detailMesh.MeshCount < 1)
            {
                mContext.Log(pre + "Aborted after detail mesh build."
                    + "No detail meshes generated.");
                polyMesh.RequestDisposal();
                detailMesh.RequestDisposal();
                mPrimary = null;
                mSecondary = null;
                mState = BuildState.Aborted;
                return;
            }

            mState = BuildState.Complete;
        }

    }
}
